### ISSUE TITLE
Exception while running copier

### ISSUE THREAD

**Issue by canatella** [pdm-project/copier-pdm#3]
I have this exception when running copier:
``` 
$ copier "gh:pdm-project/copier-pdm"  pybiomatx

Your project name
project_name? Format: str
🎤 [None]: pybiomatx

Your project description
project_description? Format: str
🎤 [None]: Python API for Biomatx home automation systems

Your full name
author_fullname? Format: str
🎤 [None]: Damien Merenne

Your email
author_email? Format: str
🎤 [None]: dam@cosinux.org

Your username (e.g. on GitHub)
author_username? Format: str
🎤 [None]: canatella

Your repository namespace
repository_namespace? Format: str
🎤 [{{ author_username }}]: 

Your repository name
repository_name? Format: str
🎤 [{{ project_name|lower|replace('_', '-')|replace(' ', '-') }}]: 

The name of the person/entity holding the copyright
copyright_holder? Format: str
🎤 [{{ author_fullname }}]: 

The email of the person/entity holding the copyright
copyright_holder_email? Format: str
🎤 [{{ author_email }}]: 

The copyright date
copyright_date? Format: str
🎤 [2021]: 

Your project's license
copyright_license? Format: str
🎤
(1) AFL-3.0
(2) Apache-2.0
(3) Artistic-2.0
(4) BSD-2-Clause
(5) BSD-3-Clause
(6) BSL-1.0
(7) EPL-1.0
(8) EPL-2.0
(9) EUPL-1.0
(10) EUPL-2.0
(11) AGPL-3.0
(12) GPL-2.0
(13) GPL-3.0
(14) LGPL-2.0-or-later
(15) LGPL-3.0
(16) ISC
(17) MIT
(18) MPL-2.0
(19) NCSA
(20) OFL-1.1
(21) OSL-3.0
(22) PostgreSQL
(23) Unlicense
(24) Zlib
Choice [17]: 

Your Python package distribution name (for `pip install NAME`)
python_package_distribution_name? Format: str
🎤 [{{ project_name|lower|replace('_', '-')|replace(' ', '-') }}]: biomatx

Your Python package import name (for `import NAME` in Python code)
python_package_import_name? Format: str
🎤 [{{ project_name|lower|replace('-', '_')|replace(' ', '_') }}]: biomatx

The python version range your project supports
python_package_requires_python? Format: str
🎤 [>=3.6]: >=3.9

Do you want to include a doc site?
build_doc? Format: bool
🎤? [y/N] 

    create  .gitignore
    create  {{_copier_conf.answers_file}}
    create  .pre-commit-config.yaml
Something went wrong. Removing destination folder.
Traceback (most recent call last):
  File "/home/dam/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/plumbum/cli/application.py", line 614, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/plumbum/cli/application.py", line 609, in run
    retcode = inst.main(*tailargs)
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/cli.py", line 38, in _wrapper
    return method(*args, **kwargs)
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/cli.py", line 252, in main
    self.parent._copy(template_src, destination_path)
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/cli.py", line 173, in _copy
    return copy(
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 147, in copy
    copy_local(conf=conf)
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 202, in copy_local
    render_file(conf, rel_path, source_path, render, must_skip)
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 394, in render_file
    content = render(src_path)
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/tools.py", line 162, in __call__
    tmpl = self.env.get_template(str(relpath))
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/dam/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 68, in template
jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag
```

**Comment by canatella** [comment]
It looks like I needed the dev version of copier, that fixes it. Don't know if there is a way to make the error a bit more descriptive though ?
